dcloud_revalidate.settings:
  type: config_object
  label: 'Dcloud Revalidate Settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable revalidation'
    frontend_url:
      type: string
      label: 'Frontend URL'
    revalidate_secret:
      type: string
      label: 'Revalidation Secret'