name: 'Drupal Cloud Core'
description: 'Drupal Cloud headless CMS configuration with GraphQL, OAuth, and modern content tools.'
type: 'Site'
recipes:
  - core/recipes/basic_shortcuts
  - core/recipes/article_tags
  - core/recipes/article_content_type
  - core/recipes/page_content_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/core_recommended_performance
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_admin_theme
  # Provides a fallback text format which is available to all users.
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role

install:
  # Core modules for modern Drupal
  - ckeditor5
  - config
  - content_moderation
  - help
  - datetime
  - datetime_range
  - field_ui
  - file
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - shortcut
  - taxonomy


  # URL and path management
  - pathauto
  - token

config:
  import:
    # Core configuration imports
    editor: '*'
    file: '*'
    media_library:
      - core.entity_view_mode.media.media_library
      - core.entity_form_mode.media.media_library
      - image.style.media_library
      - views.view.media_library
    media:
      - core.entity_view_mode.media.full
      - system.action.media_delete_action
      - system.action.media_publish_action
      - system.action.media_save_action
      - system.action.media_unpublish_action
      - views.view.media
    image:
      - image.style.medium
      - image.style.large
      - image.style.thumbnail
    menu_ui: '*'
    node:
      - views.view.content
      - views.view.content_recent
    datetime: '*'
    views: '*'
    views_ui: '*'


    # Path and URL configuration
    pathauto: '*'
    token: '*'



  actions:

    # Configure pathauto for clean URLs
    pathauto.settings:
      simple_config_update:
        enabled_entity_types:
          - node
          - taxonomy_term
        punctuation.hyphen: 1

    # Set Gin as both default and admin theme
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'gin'
