name: 'Drupal Cloud Core'
description: 'Drupal Cloud headless CMS configuration with GraphQL, OAuth, and modern content tools.'
type: 'Site'
recipes:
  - core/recipes/basic_shortcuts
  - core/recipes/article_tags
  - core/recipes/article_content_type
  - core/recipes/page_content_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/core_recommended_performance
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_admin_theme
  # Provides a fallback text format which is available to all users.
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role

install:
  # Core modules for modern Drupal
  - ckeditor5
  - config
  - content_moderation
  - help
  - datetime
  - datetime_range
  - field_ui
  - file
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - shortcut
  - taxonomy

  # Content structure modules
  - paragraphs
  - entity_reference_revisions
  - field_group

  # URL and path management
  - pathauto
  - token

  # Admin experience with Gin theme
  - gin
  - gin_login
  - gin_toolbar

  # Admin toolbar for enhanced navigation
  - admin_toolbar
  - admin_toolbar_tools

config:
  strict:
    # Treat field storages strictly, since they influence the database layout.
    - field.storage.node.field_hero_title
    - field.storage.node.field_hero_subtitle
    - field.storage.node.field_hero_description
    - field.storage.node.field_primary_cta
    - field.storage.node.field_secondary_cta
    - field.storage.node.field_features_title
    - field.storage.node.field_features_subtitle
    - field.storage.node.field_features_items
    - field.storage.node.field_cta_title
    - field.storage.node.field_cta_description
    - field.storage.node.field_cta_primary
    - field.storage.node.field_cta_secondary
    # Paragraph field storages for feature items
    - field.storage.paragraph.field_feature_title
    - field.storage.paragraph.field_feature_description
    - field.storage.paragraph.field_feature_icon

  import:
    # Core configuration imports
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    editor: '*'
    file: '*'
    field_ui: '*'
    media_library:
      - core.entity_view_mode.media.media_library
      - core.entity_form_mode.media.media_library
      - image.style.media_library
      - views.view.media_library
    media:
      - core.entity_view_mode.media.full
      - system.action.media_delete_action
      - system.action.media_publish_action
      - system.action.media_save_action
      - system.action.media_unpublish_action
      - views.view.media
    image:
      - image.style.medium
      - image.style.large
      - image.style.thumbnail
    menu_ui: '*'
    node:
      - views.view.content
      - views.view.content_recent
    datetime: '*'
    views: '*'
    views_ui: '*'

    # Content modules
    paragraphs: '*'

    # Path and URL configuration
    pathauto: '*'
    token: '*'


    # Gin admin theme configuration
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_toolbar: '*'
    gin_login: '*'

  actions:
    # Set Gin as both default and admin theme
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'gin'

    # Use admin theme for content editing
    node.settings:
      simple_config_update:
        use_admin_theme: true

    # Configure Gin blocks for better admin experience
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true

    # Configure pathauto for clean URLs
    pathauto.settings:
      simple_config_update:
        enabled_entity_types:
          - node
          - taxonomy_term
        punctuation.hyphen: 1
