next.settings:
  type: config_object
  label: 'Next.js settings'
  mapping:
    base_url:
      type: string
      label: 'Base URL'
    revalidate_secret:
      type: string
      label: 'Revalidate secret'
