name: 'DC Admin'
description: 'Modern admin interface with Gin theme and admin toolbar for enhanced content management experience.'
type: 'Site'

install:
  # Block module required for block configuration
  - block
  - help

  # Admin experience with Gin theme
  - gin
  - gin_login
  - gin_toolbar

  # Admin toolbar for enhanced navigation
  - admin_toolbar
  - admin_toolbar_tools

config:
  import:
    # Admin toolbar configuration
    admin_toolbar: '*'
    admin_toolbar_tools: '*'

    # Gin admin theme configuration
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_toolbar: '*'
    gin_login: '*'

  actions:

    # Use admin theme for content editing
    node.settings:
      simple_config_update:
        use_admin_theme: true

    # Configure Gin blocks for better admin experience
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
