dcloud.admin_category:
  title: 'Drupal Cloud'
  description: 'Drupal Cloud integration and configuration'
  parent: system.admin_config
  route_name: dcloud.admin_category
  weight: -10

dcloud_config.admin:
  title: 'Configuration'
  description: 'Configure Drupal Cloud integration settings and view OAuth credentials'
  parent: dcloud.admin_category
  route_name: dcloud_config.admin
