name: 'DCloud Configuration Helper'
type: module
description: 'Provides configuration instructions and OAuth credentials for DCloud integration'
core_version_requirement: ^10 || ^11
package: 'DCloud'
dependencies:
  - simple_oauth
  - consumers
