dcloud_config.admin:
  path: '/admin/config/services/dcloud-config'
  defaults:
    _controller: '\Drupal\dcloud_config\Controller\DcloudConfigController::configPage'
    _title: 'Drupal Cloud Configuration'
  requirements:
    _permission: 'administer dcloud configuration'

dcloud_config.homepage:
  path: '/dcloud-config'
  defaults:
    _controller: '\Drupal\dcloud_config\Controller\DcloudConfigController::homePage'
    _title: 'Drupal Cloud Configuration'
  requirements:
    _access: 'TRUE'

dcloud_config.generate_secret:
  path: '/dcloud-config/generate-secret'
  defaults:
    _controller: '\Drupal\dcloud_config\Controller\DcloudConfigController::generateSecret'
    _title: 'Generate Revalidation Secret'
  requirements:
    _access: 'TRUE'
  methods: [POST]

dcloud_config.generate_secret_ajax:
  path: '/dcloud-config/generate-secret-ajax'
  defaults:
    _controller: '\Drupal\dcloud_config\Controller\DcloudConfigController::generateSecretAjax'
    _title: 'Generate Secret Ajax'
  requirements:
    _access: 'TRUE'
  methods: [POST]
