dcloud_config.admin:
  title: 'Drupal Cloud Configuration'
  description: 'Configure Drupal Cloud integration settings and view OAuth credentials'
  parent: system.admin_config_services
  route_name: dcloud_config.admin
